{'work_dir': './work_dir/recognition/kinetics_skeleton/ST_GCN',
 'config': 'config/st_gcn/kinetics-skeleton/train.yaml',
 'phase': 'train',
 'save_result': False,
 'start_epoch': 0,
 'num_epoch': 50,
 'use_gpu': True,
 'device': [0],
 'log_interval': 100,
 'save_interval': 10,
 'eval_interval': 5,
 'save_log': True,
 'print_log': True,
 'pavi_log': False,
 'feeder': 'feeder.feeder.Feeder',
 'num_worker': 4,
 'train_feeder_args': {'random_choose': True,
                       'random_move': True,
                       'window_size': 150,
                       'data_path': './train_data.npy',
                       'label_path': './train_label.pkl',
                       'debug': False},
 'test_feeder_args': {'data_path': './val_data.npy',
                     'label_path': './val_label.pkl'},
 'batch_size': 16,
 'test_batch_size': 16,
 'debug': False,
 'model': 'net.st_gcn.Model',
 'model_args': {'in_channels': 3,
            'num_class': 400,
            'edge_importance_weighting': True,
            'graph_args': {'layout': 'openpose',
                            'strategy': 'spatial'}},
 'weights': None,
 'ignore_weights': [],
 'show_topk': [1, 5],
 'base_lr': 0.1,
 'step': [20, 30, 40, 50],
 'optimizer': 'SGD',
 'nesterov': True,
 'weight_decay': 0.0001}
 